services:
  app:
    container_name: app
    build: ./
    depends_on:
      - postgres
      - redis_db
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4"
    volumes:
      - ./app:/src/app
    ports:
      - 80:8000
    env_file:
      - .env
    restart: always

  celery:
    container_name: celery
    build: ./
    depends_on:
      - redis_db
      - postgres
      - app
    command: celery -A app.api.tasks.tasks.celery worker --loglevel=info --pool=solo
    volumes:
      - ./app:/src/celery
    env_file:
      - .env
    environment:
      DB_POSTGRES_HOST: postgres
      REDIS_HOST: ${REDIS_HOST}
    restart: always

  redis_db:
    container_name: redis_db
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - /redis_data:/data
    restart: always

  postgres:
    container_name: postgres
    image: postgres
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRES_USER: ${DB_POSTGRES_USERNAME}
      POSTGRES_DB: ${DB_POSTGRES_NAME}
    ports:
      - ${DB_POSTGRES_PORT}:5432
    volumes:
      - .postgres:/var/lib/postgresql/data
    restart: always

