services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    env_file: ../.env
    environment:
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRES_USER: ${DB_POSTGRES_USERNAME}
      POSTGRES_DB: ${DB_POSTGRES_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    container_name: app
    image: lastdaywithlesss/myapp:latest 
    restart: always
    env_file: ../.env
    environment:
      POSTGRES_HOST: ${DB_POSTGRES_HOST}
    command: bash -c 'uvicorn app.main:app --host 0.0.0.0 --port 8000'
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      - postgres
      
volumes:
  pg_data: