version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    env_file: ../.env
    environment:
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRES_USER: ${DB_POSTGRES_USERNAME}
      POSTGRES_DB: ${DB_POSTGRES_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql
    networks:
      - backend
  app:
    restart: always
    image: useruseruser2232323/shortul:latest
    command: bash -c 'uvicorn app.main:app --host 0.0.0.0 --port 8000'
    env_file: ../.env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DELAY: 5
    ports:
      - 8000:8000
    depends_on:
      - postgres
    networks:
      - backend
volumes:
  postgres-db:

networks:
  backend:
    driver: bridge
