services:
  app:
    container_name: app
    build: ./
    depends_on:
      - postgres
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4"
    volumes:
      - ./app:/src/app
    ports:
      - 80:8000
    env_file:
      - .env
    restart: always


  postgres:
    container_name: postgres
    image: postgres
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRES_USER: ${DB_POSTGRES_USERNAME}
      POSTGRES_DB: ${DB_POSTGRES_NAME}
    ports:
      - ${DB_POSTGRES_PORT}:5432
    volumes:
      - .postgres:/var/lib/postgresql/data
    restart: always

