version: '3.9'

services:
  db:
    container_name: postgres_lab2
    restart: always
    image: postgres:15
    env_file:
      - ../.env
    environment:
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRES_USER: ${DB_POSTGRES_USERNAME}
      POSTGRES_DB: ${DB_POSTGRES_NAME}

  redis:
    image: redis:7
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - ../.env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  celery:
    image: kate539/lab2:1.0
    command: celery -A app.worker.celery worker --loglevel=info
    env_file:
      - ../.env
    environment:
      DB_POSTGRES_HOST: db
      REDIS_HOST: redis

  app:
    image: kate539/lab2:1.0
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8080 --workers 4"
    env_file:
      - ../.env
    environment:
      DB_POSTGRES_HOST: db
      REDIS_HOST: redis
    ports:
      - "80:8080"

