version: "3.7"

services:
  postgres:
    container_name: postgres
    image: postgres:16.2
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: "${DB_POSTGRES_NAME}"
      POSTGRES_USER: "${DB_POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${DB_POSTGRES_PASSWORD}"
    ports:
      - "${DB_POSTGRES_PORT}:5432"
    volumes:
      - postgres-db:/var/lib/postgresql
    networks:
      - backend

  app:
    restart: always
    build:
      context: ..
      dockerfile: ./infra/Dockerfile
    env_file:
      - ../.env
    command: bash -c 'uvicorn app.main:app --host 0.0.0.0 --port 8000'
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DELAY: 5
    ports:
      - 8000:8000
    depends_on:
      - postgres
    networks:
      - backend
volumes:
  postgres-db:

networks:
  backend:
    driver: bridge