version: "3.9"

services:
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_DB: "${DB_POSTGRES_NAME}"
      POSTGRES_USER: "${DB_POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${DB_POSTGRES_PASSWORD}"
    env_file:
      - .env
    ports:
      - "${DB_POSTGRES_PORT}:5432"

  app:
    restart: always
    image: ryksovv/url-app 
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8080"
    env_file:
      - ../.env
    ports:
      - "${APP_EXTERNAL_PORT}:8080"