version: "3.9"

services:
  postgres:
    image: postgres:13.3
    env_file: .env
    environment:
      POSTGRES_DB: "${DB_POSTGRES_NAME}"
      POSTGRES_USER: "${DB_POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${DB_POSTGRES_PASSWORD}"

  app:
    image: 7embond/url-app:v1.0
    restart: always
    command: sh -c "uvicorn app.main:app --port 8080"
    env_file:
      - ../.env
    ports:
      - "${APP_EXTERNAL_PORT}:8080"