version: "3.9"

services:
  postgres:
    image: postgres:16.2
    env_file: .env
    environment:
      POSTGRES_DB: "${DB_POSTGRES_NAME}"
      POSTGRES_USER: "${DB_POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${DB_POSTGRES_PASSWORD}"
    ports:
      - "${DB_POSTGRES_PORT}:5432"