services:
  postgres:
    image: postgres:16.2
    env_file:
      - .env
    environment:
      POSTGRES_DB: "lab3"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    ports:
      - "${db_postgres_port}:5432"
    volumes:
      - ./database:/var/lib/postgresql/data

  url:
    container_name: url
    image: monuri4/lab3:1.0
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8080"
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres-data: